# Generated by Django 5.2.3 on 2025-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French"), ("ar", "Arabic")],
                default="en",
                max_length=2,
            ),
        ),
    ]
