# Generated by Django 5.2.3 on 2025-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French"), ("ar", "Arabic")],
                default="en",
                max_length=2,
            ),
        ),
    ]
