# Generated by Django 5.2.3 on 2025-07-02 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
