# Generated by Django 5.2.3 on 2026-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_variation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="🏷️",
                help_text="Add an emoji icon for this category (e.g., 👗, 👞, 👜)",
                max_length=10,
            ),
        ),
    ]
